### ISSUE TITLE
Is this more efficient than opencv FAST detector?

### ISSUE THREAD

**Issue by voyage19941119** [uzh-rpg/fast#9]

**Comment by baliika** [comment]
hello voyage19941119,
The official opencv repository contains an AVX2 optimized version of the FAST feature detector. If your platform is x86 AND the image if properly aligned in memory, then it is likely that the OpenCV version is going to be faster. On platforms where this SIMD instruction set is not supported only SSE2, then it could perform faster. 
If your platform has a CUDA-enabled graphics card, you might want to give our implementation a look: https://github.com/uzh-rpg/vilib .

**Comment by voyage19941119** [comment]
@baliika   Thanks for the reply!
